#include "A.h"




void A::perimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--66-1--5238db63:16deef9a2c4:-8000:00000000000008D4 begin
{
}
// section -64--88--66-1--5238db63:16deef9a2c4:-8000:00000000000008D4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
